### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by AndrewKlay** [cakechaser/obsidian-release-timeline#1]
Would it be possible to make this plugin even better by adding support for note aliases? Thanks in advance.

**Comment by cakechaser** [comment]
That's something I thought about, not just supporting aliases, but any field from the metadata, but didn't include in the initial release.

The query would accept 2 fields, field with date and optional field with note alias:
```
table
field_with_date, field_with_alias
from ...
```

There are 2 things to mention here:
1. If a note doesn't have a value in the specified field with alias, then the regular note name will be used instead.
2. If a note has multiple aliases in a form of `["alias1", "alias2"]` or `alias1, alias2`, then the first one will be shown on the timeline, in this case `alias1`.

Would this fit your use-case?

Thanks!

**Comment by AndrewKlay** [comment]
Thanks for the fast response, yeah, this should do the trick! My primary use is exactly like your example – video game release timelines, and with support of aliases I can use proper titles with colons, which is still a no-no for Obsidian.

**Comment by cakechaser** [comment]
Perfect! I had the same pain with the colons, but got too lazy to implement this feature, haha.
I'll target this feature for the next release then.

**Comment by cakechaser** [comment]
Just added note alias support in 1.0.4, please check if it works for you.

Example of how a query could look like:
```release-timeline
table 
release_year, alias_name
from [[CRPG]] and [[Isometric games]]
sort desc
```

**Comment by AndrewKlay** [comment]
Test was successful, works like a charm!
