### ISSUE TITLE
Two digit years display as some time in the 1900s or early 2000s

### ISSUE THREAD

**Issue by Mazarkus** [cakechaser/obsidian-release-timeline#11]
I'm working on a timeline for a story, and I'm trying to put in events that happen in say the year 50.  If used like this, it displays as the year 1950 instead, assuming I mean "the 50's" in our own timeline.

I've tested this for a few years between 0-99:
0 --> 2000
1--> 2001
99 --> 1999
etc

Is it possible to bypass this shortcut and let me define two-digit years?

**Comment by cakechaser** [comment]
@Mazarkus, thanks for reporting, I will look into this!

**Comment by cakechaser** [comment]
@Mazarkus, just fixed this in the latest release, let me know if it now works for you!

**Comment by Mazarkus** [comment]
Looks to be working, thank you!

**Comment by cakechaser** [comment]
Fixed in 1.0.7
