### ISSUE TITLE
[Bug] Cannot recognize time formats without hours and minutes.

### ISSUE THREAD

**Issue by wwjCMP** [cakechaser/obsidian-release-timeline#14]
2021-06-03 15:08 can be recognized

2021-06-03 can't be recognized

**Comment by cakechaser** [comment]
Did you mean the other way around?
Also for which type of timeline you are referring to? (year/month/week)

I've created 2 notes:
- "note - date and time" with "2021-06-03 15:08" value
- "note - date" with "2021-06-03" value

Indeed, "note - date and time" is not displayed in the weekly timeline, which is something I will look into fixing. Is this the issue you're referring to?

<img width="338" alt="image" src="https://github.com/cakechaser/obsidian-release-timeline/assets/16690476/c6d2e933-058c-4f50-b84d-e12d1203c367">

**Comment by wwjCMP** [comment]
It is strange. In my case, 'note-date' cannot be recognized, while 'note-date and time' can be recognized.

My Query is as follows. 

```release-timeline
table 
created
from #CO2RR
where created > 2000
sort desc
```

**Comment by cakechaser** [comment]
I was able to reproduce this on my side with your query, yes.

I'll check how this can be fixed, but for now as a workaround you could change the `where` condition to:
`where created > date(2000-01-01)`

**Comment by wwjCMP** [comment]
thx
