### ISSUE TITLE
README images don't load from Obsidian

### ISSUE THREAD

**Issue by liamcain** [cakechaser/obsidian-release-timeline#2]
Sorry I didn't catch this earlier during review. In your README.md, you will want to update the images to point to the github CDN. For example: <https://raw.githubusercontent.com/cakechaser/obsidian-release-timeline/75031c81e0226609ca9db7a0fcf437730769a443/assets/bullets.png>

This is because Obsidian will only download and render the README file, not the assets, so for them to show up properly in the gallery, the `<img>` tags need to resolve to the fully qualified github path.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/693981/169841006-91c1533d-9755-4c9a-a0e2-c71fdca73eed.png">

**Comment by cakechaser** [comment]
@liamcain, just fixed, now images show up in community plugins list in Obsidian.
Thank you for the notice!
