### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by jsmm** [cakechaser/obsidian-release-timeline#3]
I get the following: `Error from dataview: Cannot read properties of null (reading 'toString')`. It is querying for a field named `published` in front matter, with values in format 2022-05-24. 
The same query works when if I change only `release-timeline` for `dataview`.
Thanks.

**Comment by cakechaser** [comment]
@jsmm, Are there by any chance some notes that have the field `published` in the front matter, but no value for it?
I just found that this causes a similar error, published a new version 1.0.3 with the fix.

Please let me know if it solves the issue.
