### ISSUE TITLE
From Querys not working on Windows

### ISSUE THREAD

**Issue by lovwyr** [cakechaser/obsidian-release-timeline#6]
Hi, i noticed while experimenting that the From "$Foldername" querys do not work. 

![grafik](https://user-images.githubusercontent.com/2073192/172013440-b3a1d886-9f08-4615-b7a9-218c34b6b248.png)
![grafik](https://user-images.githubusercontent.com/2073192/172013466-d48a0d35-6775-4c30-ab1e-012528520db9.png)

The problem comes from the 
`content = content.replace(/[\r\n]+/g," ").toLocaleLowerCase();`

in the [renderTimeline ](https://github.com/cakechaser/obsidian-release-timeline/blob/ddc605ef6960c806db33369a8441496982969638/functions.ts#L248) function, a change to:
`content = content.replace(/[\r\n]+/g," ");`

fixes the problem.

**Comment by cakechaser** [comment]
@lovwyr, just fixed this in the latest release, let me know if it works for you.

**Comment by lovwyr** [comment]
@cakechaser, can confirm that is working correctly right now. Thanks for the afford :)
