### ISSUE TITLE
Unable to omit FROM statement

### ISSUE THREAD

**Issue by evitiello** [cakechaser/obsidian-release-timeline#7]
I have a dataview query that lists all of my pages, which works fine as a Dataview query, but returns the error:

*Error parsing the 'FROM' statement*

The query in question is:

```release-timeline
TABLE EventStartDate as "Date", Blurb as "Description"
WHERE EventStartDate > date(1000-01-01)
SORT EventStartDate DESC
```

**Comment by cakechaser** [comment]
I didn't consider queries without the FROM statement, true. Currently re-writing the plugin to support any query execution (including WHERE statements), should be done soon, will let you know here.

**Comment by cakechaser** [comment]
@evitiello, just fixed this in the latest release. Let me know if it works now.

**Comment by evitiello** [comment]
Verified, all fixed.
