### ISSUE TITLE
results not sorted correctly when using ISO 8601 date format

### ISSUE THREAD

**Issue by nousernameavailableanymore** [cakechaser/obsidian-release-timeline#9]
My dates are formated in ISO 8601 in YAML (for example 2022-09-27).
When creating a simple table the results within a month are not sorted by the value in the "date" YAML field but rather seem to be sorted (at least within a month) by the modified date.

I can easily make the results for September change places by modifying any of the notes
Not sorted correctly:
![image](https://user-images.githubusercontent.com/45376324/192404905-5e2c4d42-27b6-4c2d-8759-f9eb251ef75d.png)

Result after modifying the 2022-09-22 node:
![image](https://user-images.githubusercontent.com/45376324/192405212-46fd5000-e199-4cbc-a80c-bea790df8d47.png)

(Disregard the 2022-09-10 node in the August results, that node was named incorrectly, the "date was set to 2022-08-30". All other "date" values equal the file names.)

Not sure if this only applies to this specific date format and / or the "month" option.

Query:
```release-timeline-month
table
date
from #some_tag
```

**Comment by cakechaser** [comment]
This is now fixed in the latest release.
Thanks for reporting!
